/**
 * TypeScript type definition tests
 *
 * This file is compiled by TypeScript during testing to verify that:
 * 1. The generated .d.ts files are valid
 * 2. Types are correctly exported and usable
 * 3. Type inference works as expected
 *
 * This file is NOT executed—it only needs to type-check successfully.
 */

import { minify, type MinifierOptions, type HTMLAttribute } from '../src/htmlminifier.js';

// Test: minify function basic usage
async function testBasicMinify() {
  const html = '<div>  test  </div>';

  // Should accept string and return Promise<string>
  const result: string = await minify(html);

  // Should accept options
  const result2: string = await minify(html, {
    collapseWhitespace: true,
    removeComments: true,
  });

  return result;
}

// Test: all boolean options
async function testBooleanOptions() {
  const html = '<div>test</div>';

  const options: MinifierOptions = {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: false,
    collapseWhitespace: true,
    conservativeCollapse: false,
    continueOnMinifyError: true,
    continueOnParseError: true,
    decodeEntities: false,
    html5: true,
    includeAutoGeneratedTags: true,
    keepClosingSlash: false,
    noNewlinesBeforeTagClose: false,
    preserveLineBreaks: true,
    preventAttributesEscaping: false,
    processConditionalComments: false,
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyElements: false,
    removeOptionalTags: false,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: false,
    trimCustomFragments: false,
    useShortDoctype: true,
  };

  return await minify(html, options);
}

// Test: minifyCSS option types
async function testMinifyCSSOptions() {
  const html = '<style>body { color: red; }</style>';

  // Boolean
  await minify(html, { minifyCSS: true });

  // Note: Object options (Lightning CSS TransformOptions) are supported at runtime
  // but require internal properties (filename, code) that the minifier adds automatically,
  // so they cannot be properly type-checked here. Use Boolean or function types instead.

  // Function
  await minify(html, {
    minifyCSS: (text: string, type?: string) => {
      return text.replace(/\s+/g, ' ');
    },
  });

  // Async function
  await minify(html, {
    minifyCSS: async (text: string, type?: string) => {
      return Promise.resolve(text.trim());
    },
  });
}

// Test: minifyJS option types
async function testMinifyJSOptions() {
  const html = '<script>var x = 1;</script>';

  // Boolean
  await minify(html, { minifyJS: true });

  // Object (Terser options)
  await minify(html, {
    minifyJS: {
      mangle: false,
      compress: { drop_console: true },
    },
  });

  // Function
  await minify(html, {
    minifyJS: (text: string, inline?: boolean) => {
      return text.replace(/\s+/g, ' ');
    },
  });

  // Async function
  await minify(html, {
    minifyJS: async (text: string, inline?: boolean) => {
      return Promise.resolve(text.trim());
    },
  });
}

// Test: minifyURLs option types
async function testMinifyURLsOptions() {
  const html = '<a href="/path/to/page.html">Link</a>';

  // Boolean
  await minify(html, { minifyURLs: true });

  // String (site)
  await minify(html, { minifyURLs: 'https://example.com' });

  // Object (relateurl options)
  await minify(html, {
    minifyURLs: {
      site: 'https://example.com',
    },
  });

  // Function
  await minify(html, {
    minifyURLs: (text: string) => {
      return text.toLowerCase();
    },
  });

  // Async function
  await minify(html, {
    minifyURLs: async (text: string) => {
      return Promise.resolve(text.toLowerCase());
    },
  });
}

// Test: RegExp array options
async function testRegExpOptions() {
  const html = '<div ng-click="test()">test</div>';

  const options: MinifierOptions = {
    customAttrAssign: [/\?=/],
    customEventAttributes: [/^ng-/, /^on[a-z]+$/],
    ignoreCustomComments: [/^!/, /^#/],
    ignoreCustomFragments: [/<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/],
  };

  return await minify(html, options);
}

// Test: custom surround patterns
async function testCustomAttrSurround() {
  const html = '<input {{#if value}}checked{{/if}}>';

  const options: MinifierOptions = {
    customAttrSurround: [
      [/\{\{#if\s+\w+\}\}/, /\{\{\/if\}\}/],
      [/\{\{#unless\s+\w+\}\}/, /\{\{\/unless\}\}/],
    ],
  };

  return await minify(html, options);
}

// Test: function options
async function testFunctionOptions() {
  const html = '<div class="b a c">test</div>';

  const options: MinifierOptions = {
    log: (message: unknown) => {
      console.log(message);
    },
    name: (name: string) => name.toLowerCase(),
    canCollapseWhitespace: (tag, attrs, canCollapseWhitespace) => {
      return tag !== 'pre';
    },
    canTrimWhitespace: (tag, attrs, canTrimWhitespace) => {
      return tag !== 'textarea';
    },
    removeEmptyAttributes: (attrName: string, tag: string) => {
      return attrName !== 'alt';
    },
    sortAttributes: (tag: string, attrs: HTMLAttribute[]) => {
      attrs.sort((a, b) => a.name.localeCompare(b.name));
    },
    sortClassName: (value: string) => {
      return value.split(' ').sort().join(' ');
    },
  };

  return await minify(html, options);
}

// Test: number options
async function testNumberOptions() {
  const html = '<div>test</div>';

  const options: MinifierOptions = {
    maxInputLength: 1000000,
    maxLineLength: 80,
    customFragmentQuantifierLimit: 200,
  };

  return await minify(html, options);
}

// Test: array options
async function testArrayOptions() {
  const html = '<script type="text/ng-template"><div>test</div></script>';

  const options: MinifierOptions = {
    processScripts: ['text/ng-template', 'text/x-handlebars-template'],
    inlineCustomElements: ['my-element', 'custom-widget'],
  };

  return await minify(html, options);
}

// Test: quote character option
async function testQuoteCharacter() {
  const html = '<div class="test">content</div>';

  // Should only accept specific string literals
  await minify(html, { quoteCharacter: '"' });
  await minify(html, { quoteCharacter: "'" });

  // Note: TypeScript correctly restricts quoteCharacter to only '"' or "'"
  // Any other value would be a type error
}

// Test: HTMLAttribute type
function testHTMLAttributeType() {
  const attr: HTMLAttribute = {
    name: 'class',
    value: 'test',
    quote: '"',
  };

  const attrMinimal: HTMLAttribute = {
    name: 'disabled',
  };

  const attrCustom: HTMLAttribute = {
    name: 'ng-click',
    value: 'doSomething()',
    customAssign: '?=',
    customOpen: '{{',
    customClose: '}}',
  };

  return [attr, attrMinimal, attrCustom];
}

// Test: Type inference works
async function testTypeInference() {
  // Should infer return type as Promise<string>
  const result = await minify('<div>test</div>', {
    collapseWhitespace: true,
  });

  // result should be inferred as string
  const length: number = result.length;

  return result;
}

// Test: Complex real-world usage
async function testRealWorldUsage() {
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { margin: 0; padding: 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>Title</h1>
          <p>Content</p>
        </div>
        <script>
          console.log('Hello');
        </script>
      </body>
    </html>
  `;

  const result = await minify(html, {
    collapseWhitespace: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    useShortDoctype: true,
    minifyCSS: true,
    minifyJS: {
      compress: {
        drop_console: false,
      },
    },
    sortClassName: true,
  });

  return result;
}

// Export to avoid "unused" warnings
export {
  testBasicMinify,
  testBooleanOptions,
  testMinifyCSSOptions,
  testMinifyJSOptions,
  testMinifyURLsOptions,
  testRegExpOptions,
  testCustomAttrSurround,
  testFunctionOptions,
  testNumberOptions,
  testArrayOptions,
  testQuoteCharacter,
  testHTMLAttributeType,
  testTypeInference,
  testRealWorldUsage,
};