name: "Benchmarks"

on: workflow_dispatch

env:
  NODE_VERSION: lts/*

jobs:
  benchmark:
    name: "Benchmarks"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out"
        uses: actions/checkout@v4

      - name: "Use Node.js ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: "Install dependencies"
        run: npm ci

      - name: "Install benchmark dependencies"
        run: npm ci
        working-directory: ./benchmarks

      - name: "Run benchmarks"
        run: npm run benchmarks
        working-directory: ./benchmarks

      - name: "Create pull request"
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: benchmarks
          title: Update benchmarks
          body: |
            Update benchmarks
          add-paths: |
            README.md